### ISSUE TITLE
Merged resourcepack produces invalid shader (rendertype_entity_translucent) on 1.20.4 clients with Iris (works on 4.0.10-hotfix-1)

### ISSUE THREAD

**Issue by xcoolerboy** [PluginBugs/Issues-ItemsAdder#4988]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### What happened?

After updating from ItemsAdder v4.0.10-hotfix-1 to newer versions, the merged resourcepack fails to load on 1.20.4 Fabric clients if Iris is enabled.
This issue did not occur on 4.0.10-hotfix-1 — suggesting that the resourcepack merging logic introduced afterward is generating shader JSON/GLSL code that cannot compile on clients.

Error (client log excerpt):

Caused by: ahj: Invalid shaders/core/rendertype_entity_translucent.json: Couldn't compile vertex program (file/another prison.zip, rendertype_entity_translucent)
0(73) : error C1102: incompatible type for parameter #1 ("modelViewMat.21")
0(73) : error C7011: implicit cast from "int" to "vec3"
0(73) : error C1103: too few parameters in function call

After this, the client forcibly unloads all resourcepacks:

Caught error loading resourcepacks, removing all selected resourcepacks

### Steps to reproduce the issue

merge resourcepack on 4.0.11 itemsadder and try to load that resourcepack on 1.20.4 client

### Server version

1.21.1

### ItemsAdder Version

4.0.11

### ProtocolLib Version

5.4.0

### Full Server Log

https://pastes.dev/zAxjSuyyqn       here is client log

### Error (optional)

```shell

```

### Problematic items yml configuration file (optional)

```yaml

```

**Comment by LoneDev6** [comment]
After some testing seems the 1.20.4 client is missing some stuff, I will fix that.
This is fixed in the upcoming beta 7, you will have to regenerate your resourcepack.
Thanks!
