### ISSUE TITLE
Add support to CustomCrafting 2.16.2

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#1265]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When I put IA items into crafting table, console reports error.
It has been a long time since I reported this to CustomCrafting's developer. He said he had been ready to add compatibility with ItemsAdder and he had already talked to you about this.
But the fact is that IA only works with CC 1.7.1.3 but not CC 2.16.
CC 1.7.1.3 has many critical bugs and really lags the server. CC's developer has given up older version and only maintein CC 2.16.
I prefer CC because it can use other plugins' items as ingredients and results(such as mmoitems). ItemsAdder's recipes only support IA items and vanilla items.

WolfyUtilities 1.7.5.0 beta  https://www.curseforge.com/minecraft/bukkit-plugins/wolfyutilities/download/3429071
CustomCrafting 2.16.2 https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-17-premium.95513/

### Steps to reproduce the issue

When I put ia items into crafting table, console reports error.

### Server version

[23:18:53 INFO]: This server is running Purpur version git-Purpur-1415 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2df73e0 on ver/1.17.1)
[23:18:53 INFO]: You are running the latest version
[23:18:53 INFO]: Previous version: git-Purpur-1378 (MC: 1.17.1)

### ItemsAdder Version

ItemsAdder version 2.4.19b

### ProtocolLib Version

 ProtocolLib version 4.7.1-SNAPSHOT-b533

### LoneLibs Version

 LoneLibs version 1.0.15

### FULL server log

[23:15:46 ERROR]: Could not pass event PrepareItemCraftEvent to ItemsAdder v2.4.19b
java.lang.NoClassDefFoundError: me/wolfyscript/customcrafting/recipes/types/CustomRecipe
        at dev.lone.itemsadder.Core.j.c.c.a(SourceFile:244) ~[ItemsAdder.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1415]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1337) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:87) ~[app:?]
        at net.minecraft.world.inventory.CraftingMenu.lambda$slotsChanged$0(CraftingMenu.java:98) ~[app:?]
        at net.minecraft.world.inventory.ContainerLevelAccess.lambda$execute$0(ContainerLevelAccess.java:67) ~[app:?]
        at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:54) ~[app:?]
        at net.minecraft.world.inventory.ContainerLevelAccess.execute(ContainerLevelAccess.java:66) ~[app:?]
        at net.minecraft.world.inventory.CraftingMenu.slotsChanged(CraftingMenu.java:97) ~[app:?]
        at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:141) ~[app:?]
        at net.minecraft.world.inventory.Slot.set(Slot.java:61) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.world.inventory.Slot.safeInsert(Slot.java:146) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:545) ~[app:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:371) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2894) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1447) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1425) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1307) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1415]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.wolfyscript.customcrafting.recipes.types.CustomRecipe
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Purpur-1415]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 34 more

### Screenshots/Videos

(you can drag and drop files or paste links)

**Comment by LoneDev6** [comment]
It's currently not possible for me to add compatibility easily, I already asked the developer but I think we cannot add compatibility.
I'll add compatibility to the beta version when it will be a full official release or if the developer provides me a set of identical API methods for both beta and release version.

Thanks

**Comment by LoneDev6** [comment]
This was added in recent updates of ItemsAdder.
Be sure to update also CustomCrafting.
