### ISSUE TITLE
First install - first broken (java.lang.NoSuchMethodError)

### ISSUE THREAD

**Issue by NeotenySS** [PluginBugs/Issues-ItemsAdder#4313]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

cliff0951

### What happened?

I followed the installation instructions, step 1, step 2, and already step 3 just gave me an error.
Version 1.21.4 server. Client 1.21.4 and no have mods.
I bought your plugin not so long ago, previously I used Oraxen, however I would like to understand your functionality in practice, but using the texture pack from you, I get errors and do not have reliable information about what and how it works and whether it works on the new version 1.21.4, as doubts have become more, because you have not so long ago abandoned the old versions (I do not mind and even happy about this news), but at the same time, the new version still requires improvement eh...

### Steps to reproduce the issue

Perform step 1 of the installation, then step 2.
Performing step 3 using the texture pack (default_pack_2.0.10) the server will notify you of an error after reloading the plugin/server or updating the texture pack with the iazip command.
By the way, to avoid the error java.lang.NoSuchMethodError: 'org.bukkit.Keyed org.bukkit.UnsafeValues.get(org.bukkit.Registry, org.bukkit.NamespacedKey)' I simply deleted the iasurvival folder, then I changed the value in ItemsAdder\contents\iageneric\configs\items.yml, namely I replaced O: iasurvival:plastic_plate with DIAMOND.

### Server version

[17:44:21 INFO]: This server is running Paper version 1.21.4-106-main@ab1b312 (2025-01-12T23:38:01Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

[17:44:49 INFO]: ItemsAdder version 4.0.6
[17:44:49 INFO]: Customized Minecraft without client mods!
[17:44:49 INFO]: Website: devs.beer
[17:44:49 INFO]: Author: LoneDev

### ProtocolLib Version

[17:45:24 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-739
[17:45:24 INFO]: Provides read/write access to the Minecraft protocol.
[17:45:24 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[17:46:43 INFO]: LoneLibs version 1.0.63
[17:46:43 INFO]: Collection of libs used by my plugins
[17:46:43 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/Yd8LIiv

### Error (optional)

```shell
[17:37:17 WARN]: [ItemsAdder] Failed to add font glypth entry. Vanilla resource 'assets/minecraft/textures/item/broken_elytra.png' doesn't exists. File: /contents/mcemojis/configs/emoji_images.yml
[17:37:17 WARN]: [ItemsAdder] Failed to add font glypth entry. Vanilla resource 'assets/minecraft/textures/item/scute.png' doesn't exists. File: /contents/mcemojis/configs/emoji_images.yml
[17:37:18 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[17:37:18 WARN]: java.lang.NoSuchMethodError: 'org.bukkit.Keyed org.bukkit.UnsafeValues.get(org.bukkit.Registry, org.bukkit.NamespacedKey)'
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//itemsadder.m.abj.bX(SourceFile:336)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//itemsadder.m.ct.a(SourceFile:250)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//itemsadder.m.ct.ds(SourceFile:133)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//itemsadder.m.ag.b(SourceFile:703)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//itemsadder.m.ag.c(SourceFile:647)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//itemsadder.m.afc.d(SourceFile:130)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//itemsadder.m.ag.a(SourceFile:641)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//itemsadder.m.ag.l(SourceFile:296)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//dev.lone.itemsadder.Main.iZ(SourceFile:506)
[17:37:18 WARN]:        at ItemsAdder_4.0.6.jar//dev.lone.itemsadder.Main.onEnable(SourceFile:420)
[17:37:18 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:284)
[17:37:18 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[17:37:18 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[17:37:18 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[17:37:18 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:656)
[17:37:18 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:605)
[17:37:18 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
[17:37:18 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
[17:37:18 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322)
[17:37:18 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163)
[17:37:18 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
[17:37:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Problematic items yml configuration file (optional)

```yaml
mc_broken_elytra:
    permission: mc_broken_elytra
    show_in_gui: true
    path: "minecraft:item/broken_elytra"
    scale_ratio: 9
    y_position: 8
  mc_scute:
    permission: mc_scute
    show_in_gui: true
    path: "minecraft:item/scute"
    scale_ratio: 9
    y_position: 8



info:
  namespace: iageneric
recipes:
  crafting_table:
    carton_box:
      permission: iageneric.items.carton_box
      enabled: true
      pattern:
        - OOO
        - PPP
        - PPP
      ingredients:
        P: PAPER
        O: iasurvival:plastic_plate
      result:
        item: iageneric:carton_box
        amount: 1
```

### Other files, you can drag and drop them here to upload. (optional)

[error.zip](https://github.com/user-attachments/files/18398307/error.zip)

**Comment by NeotenySS** [comment]
If you are not satisfied with my archive, you can simply download your own default_pack_2.0.10 archive from your repository

**Comment by NeotenySS** [comment]
Please give me some time, I will check and provide you with an answer later on

**Comment by NeotenySS** [comment]
To my regret, the problem remains current on version 4.0.7-beta-4
[https://mclo.gs/F3Jsybl](url)

**Comment by NeotenySS** [comment]
The problem with java.lang.NoSuchMethodError is solved, I don't know yet what the problem is related to other errors, I haven't edited anything yet, maybe you can give some comment about it.
Also I reserve the right to close/open this ticket at your discretion (your decision). I think you will know whether this ticket is necessary or not.
https://mclo.gs/IlQQ4EC
