### ISSUE TITLE
Denizen command `set_custom_block` broken

### ISSUE THREAD

**Issue by BredyAK** [PluginBugs/Issues-ItemsAdder#4597]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

henry_corwn

### What happened?

Denizen command `set_custom_block` is broken, it's just not work as expected according to [https://itemsadder.devs.beer/developers/denizen-api](https://itemsadder.devs.beer/developers/denizen-api).

### Steps to reproduce the issue

1. Just use IA 4.0.10-beta-5 and install any version of Denizen
2. Execute `/ex set_custom_block <player.cursor_on> custom:red_block`

### Server version

> \> version
[16:22:38 INFO]: Checking version, please wait...
[16:22:39 INFO]: This server is running Paper version 1.21.4-224-main@0cf7315 (2025-04-07T12:01:39Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-222-9b1798d (MC: 1.21.4)

### ItemsAdder Version

> \> version ItemsAdder
[16:23:30 INFO]: ItemsAdder version 4.0.10-beta-5
[16:23:30 INFO]: Customized Minecraft without client mods!
[16:23:30 INFO]: Website: devs.beer
[16:23:30 INFO]: Author: LoneDev

### ProtocolLib Version

> \> version ProtocolLib
[16:23:55 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[16:23:55 INFO]: Provides read/write access to the Minecraft protocol.
[16:23:55 INFO]: Authors: dmulloy2 and comphenix

### Full Server Log

Bare-minimum Server Log: https://mclo.gs/rNj8qJH
Production Server Log: https://mclo.gs/9Kfcq83

### Error (optional)

There is no errors on my bare-minimum server.

Denizen debug errors on my production server:
```shell
[16:18:22 INFO]: +> [ScriptRegistry] Loading 222 script files...                                                                                             [16:18:22 INFO]: +> [DenizenCore] Scripts loaded! File load took 149ms, processing 6ms.                                                                      
[16:18:22 INFO]:  ERROR in script 'inject_stack_pebbles_block' while executing command 'SET_CUSTOM_BLOCK' in file 'scripts/global/items/ingredients/pebbles_small.dsc' on line '45'!                                                       
                 Error Message: Unknown command 'SET_CUSTOM_BLOCK'. ... Enable debug on the script for more information.                                     
[16:18:22 INFO]: +> [ScriptEvent] Processed 205 script event paths.
```

### Problematic items yml configuration file (optional)

```yaml

```

**Comment by LoneDev6** [comment]
is the command working on 4.0.9?

**Comment by LoneDev6** [comment]
They might have changed something in their code?
It's impossible that a ItemsAdder update broken the combability.
Can you downgrade ItemsAdder and test again to make sure?

Also I can't load Denizen on 1.21.4 or 1.21.3, Denizen is not loading on these versions.

```
[16:24:20 ERROR]: Error occurred while enabling Denizen v1.3.1-SNAPSHOT (build 7148-DEV) (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R4/inventory/CraftInventoryCustom 
```

**Comment by BredyAK** [comment]
> They might have changed something in their code? It's impossible that a ItemsAdder update broken the combability. Can you downgrade ItemsAdder and test again to make sure?
> 
> Also I can't load Denizen on 1.21.4 or 1.21.3, Denizen is not loading on these versions.
> 
> ```
> [16:24:20 ERROR]: Error occurred while enabling Denizen v1.3.1-SNAPSHOT (build 7148-DEV) (Is it up to date?)
> java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R4/inventory/CraftInventoryCustom 
> ```

@LoneDev6 Hi there, the last build for 1.21.4 was [https://ci.citizensnpcs.co/job/Denizen_Developmental/7144](https://ci.citizensnpcs.co/job/Denizen_Developmental/7144), any Denizen version later than that was targeted for 1.21.5.

I did another test and everything was just same as above. My tested Denizen version is 7144.

**Comment by LoneDev6** [comment]
Works fine for me on beta 7, there is something else wrong in your server

https://github.com/user-attachments/assets/4112a688-84b6-4f4e-9061-d0f49c3be9d4
