### ISSUE TITLE
MMOItems incompatibility

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-ItemsAdder#1919]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Six#6220

### What happened?

With new versions of MmoItems/MythicLib, ItemsAdder prevents the entire server from booting. I've eben informed that MMOItems class package has changed names, causing this issue.

### Steps to reproduce the issue

Try to boot server with latest IA, MMOItems and MythicLib spigot releases.

### Server version

Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### ItemsAdder Version

3.2.3f

### ProtocolLib Version

4.8.0 (I've also tried newer dev builds)

### LoneLibs Version

1.0.21

### Error (optional)

```shell
[08:46:30] [Server thread/WARN]: [ItemsAdder] Task #1334 for ItemsAdder v3.2.3f generated an exception
java.lang.NoClassDefFoundError: net/Indyuce/mmoitems/MMOItems
    at dev.lone.itemsadder.main.aB.b(SourceFile:1483) ~[ItemsAdder_3.2.3f.jar:?]
    at dev.lone.itemsadder.main.aB.a(SourceFile:583) ~[ItemsAdder_3.2.3f.jar:?]
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:103) ~[paper-1.18.2.jar:git-Paper-387]
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.18.2.jar:git-Paper-387]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.Indyuce.mmoitems.MMOItems
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
    ... 7 more

Loops this error endlessly on boot, preventing server startup.
```

**Comment by LoneDev6** [comment]
They probably changed something in their API, I will check it now.

**Comment by LoneDev6** [comment]
It works fine with MMOItems 6.8.1, I have no idea which version you have installed
